<a href="https://colab.research.google.com/github/minhtam3010050-jpg/TH_DEEP/blob/main/BT_TUAN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Min-Max Scaling & Standard Scaling

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Tạo dữ liệu giả lập (Raw Dataset)
data = {
    'Car_Price': [1000, 5000, 2500, 3000, 3500],
    'Age': [20, 40, 25, 30, 35],
    'Vehicle_Type': ['bus', 'car', 'truck', 'motorbike', 'car'],
    'Level': ['low', 'high', 'medium', 'low', 'medium'],
    'Label': ['cat', 'bird', 'cat', 'dog', 'dog']
}
df = pd.DataFrame(data)

# Tạo thêm dữ liệu Test (Out-of-distribution / Unseen categories)
test_data = {
    'Car_Price': [4500, 6000],
    'Age': [45, 50],
    'Vehicle_Type': ['car', 'bicycle'],
    'Level': ['high', 'unknown'],
    'Label': ['bird', 'dog']
}
df_test_unseen = pd.DataFrame(test_data)

print("--- Dữ liệu gốc (Train/Val Pool) ---")
display(df)
print("\n--- Dữ liệu Test thực tế (Chứa phần tử lạ) ---")
display(df_test_unseen)

#bài1: Min-Max Scaling & Standard Scaling

from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Bước 1: Chia dữ liệu trước (Split First)
X_train = df[['Car_Price', 'Age']].copy()
X_test = df_test_unseen[['Car_Price', 'Age']].copy()

print("--- Thực hành Min-Max Scaling ---")
# Bước 2: Khởi tạo và CHỈ fit trên Train
scaler_minmax = MinMaxScaler()
scaler_minmax.fit(X_train)

# Bước 3: Transform cả Train và Test bằng scaler đã fit
X_train_minmax = scaler_minmax.transform(X_train)
X_test_minmax = scaler_minmax.transform(X_test)

print("X_train sau Min-Max:\n", X_train_minmax)
print("X_test sau Min-Max (Có giá trị Out-of-bounds):\n", X_test_minmax)

print("\n--- Thực hành Standard Scaling (Z-score) ---")
# Tương tự cho StandardScaler
scaler_std = StandardScaler()
scaler_std.fit(X_train)

X_train_std = scaler_std.transform(X_train)
X_test_std = scaler_std.transform(X_test)

print("X_train sau Standardize:\n", X_train_std)
print("X_test sau Standardize:\n", X_test_std)

--- Dữ liệu gốc (Train/Val Pool) ---

   Car_Price  Age Vehicle_Type   Level Label
0       1000   20          bus     low   cat
1       5000   40          car    high  bird
2       2500   25        truck  medium   cat
3       3000   30    motorbike     low   dog
4       3500   35          car  medium   dog

--- Dữ liệu Test thực tế (Chứa phần tử lạ) ---

   Car_Price  Age Vehicle_Type    Level Label
0       4500   45          car     high  bird
1       6000   50      bicycle  unknown   dog

--- Thực hành Min-Max Scaling ---
X_train sau Min-Max:
 [[0.    0.   ]
 [1.    1.   ]
 [0.375 0.25 ]
 [0.5   0.5  ]
 [0.625 0.75 ]]
X_test sau Min-Max (Có giá trị Out-of-bounds):
 [[0.875 1.25 ]
 [1.25  1.5  ]]

--- Thực hành Standard Scaling (Z-score) ---
X_train sau Standardize:
 [[-1.53392998 -1.41421356]
 [ 1.53392998  1.41421356]
 [-0.38348249 -0.70710678]
 [ 0.          0.        ]
 [ 0.38348249  0.70710678]]
X_test sau Standardize:
 [[1.15044748 2.12132034]
 [2.30089497 2.82842712]]

One-Hot Encoding

In [15]:




# Thực hành Bài 2: One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder

# Bước 1: Chia dữ liệu trước (Split First)
X_train_cat = df[['Vehicle_Type']].copy()
X_test_cat = df_test_unseen[['Vehicle_Type']].copy()

print("\n--- Thực hành One-Hot Encoding ---")
# Bước 2: Khởi tạo với cấu hình xử lý biến lạ (handle_unknown='ignore') và CHỈ fit trên Train
encoder_ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder_ohe.fit(X_train_cat)

# Bước 3: Transform cả hai tập bằng encoder đã fit từ tập Train
X_train_ohe = encoder_ohe.transform(X_train_cat)
X_test_ohe = encoder_ohe.transform(X_test_cat)

print("Các danh mục học được từ Train:", encoder_ohe.categories_)
print("\nX_train sau One-Hot Encoding:\n", X_train_ohe)
print("\nX_test sau One-Hot Encoding (Dòng 2 chứa 'bicycle' biến thành các số 0 an toàn giống Slide 5):\n", X_test_ohe)

--- Thực hành One-Hot Encoding ---
Các danh mục học được từ Train: [array(['bus', 'car', 'motorbike', 'truck'], dtype=object)]

X_train sau One-Hot Encoding:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

X_test sau One-Hot Encoding (Dòng 2 chứa 'bicycle' biến thành các số 0 an toàn giống Slide 5):
 [[0. 1. 0. 0.]
 [0. 0. 0. 0.]]

ORDINAL ENCODING (CHO BIẾN CÓ THỨ TỰ)

In [5]:
# ==========================================
# BÀI 3: ORDINAL ENCODING (CHO BIẾN CÓ THỨ TỰ)
# ==========================================
from sklearn.preprocessing import OrdinalEncoder

print("=== BÀI 3: THỰC HÀNH ORDINAL ENCODING ===")

# Tách dữ liệu thuộc tính Level
X_train_ord = df[['Level']].copy()
X_test_ord = df_test_unseen[['Level']].copy()

# Bước 1: Khởi tạo Encoder và định nghĩa rõ ràng thứ tự (Rank) từ thấp đến cao
# handle_unknown='use_encoded_value' và unknown_value=-1 giúp xử lý các giá trị không nằm trong danh mục huấn luyện
categories_order = [['low', 'medium', 'high']]

encoder_ord = OrdinalEncoder(
    categories=categories_order,
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

# Bước 2: CHỈ fit trên tập Train
encoder_ord.fit(X_train_ord)

# Bước 3: Transform cả hai tập Train và Test
X_train_encoded = encoder_ord.transform(X_train_ord)
X_test_encoded = encoder_ord.transform(X_test_ord)

print("Thứ tự danh mục được thiết lập cố định:", encoder_ord.categories_)
print("\nX_train sau Ordinal Encoding (Thứ tự 0, 1, 2):")
print(X_train_encoded)

print("\nX_test sau Ordinal Encoding (Chứa 'unknown' được gán bằng -1 an toàn):")
print(X_test_encoded)

=== BÀI 3: THỰC HÀNH ORDINAL ENCODING ===
Thứ tự danh mục được thiết lập cố định: [array(['low', 'medium', 'high'], dtype=object)]

X_train sau Ordinal Encoding (Thứ tự 0, 1, 2):
[[0.]
 [1.]
 [2.]
 [0.]
 [1.]]

X_test sau Ordinal Encoding (Chứa 'unknown' được gán bằng -1 an toàn):
[[ 2.]
 [-1.]]

XÂY DỰNG PIPELINE HOÀN CHỈNH

In [6]:
# ==========================================
# BÀI 4: XÂY DỰNG PIPELINE HOÀN CHỈNH
# ==========================================
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier # Thêm một mô hình giả định làm ví dụ

print("\n=== BÀI 4: XÂY DỰNG PIPELINE TỰ ĐỘNG CHỐNG RÒ RỈ ===")

# Phân loại danh sách các đặc trưng (Features)
numeric_features = ['Car_Price', 'Age']
nominal_features = ['Vehicle_Type']
ordinal_features = ['Level']

# Định nghĩa thứ tự cho biến Ordinal giống như Bài 3
categories_order = [['low', 'medium', 'high']]

# 1. Khởi tạo ColumnTransformer - Định nghĩa cách tiền xử lý cho từng nhóm cột cụ thể
preprocessor = ColumnTransformer(
    transformers=[
        # Nhóm số học: Chuẩn hóa bằng MinMaxScaler
        ('num', MinMaxScaler(), numeric_features),

        # Nhóm danh mục định danh: Mã hóa bằng OneHotEncoder, bỏ qua giá trị lạ
        ('cat_nominal', OneHotEncoder(handle_unknown='ignore', sparse_output=False), nominal_features),

        # Nhóm danh mục thứ tự: Mã hóa bằng OrdinalEncoder, gán -1 cho giá trị lạ
        ('cat_ordinal', OrdinalEncoder(categories=categories_order, handle_unknown='use_encoded_value', unknown_value=-1), ordinal_features)
    ]
)

# 2. Đóng gói bộ Tiền xử lý (Preprocessor) và Mô hình (Model) vào một Pipeline duy nhất
full_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(random_state=42)) # Thay thế bằng bất kỳ mô hình nào bạn muốn
    ]
)

# Chuẩn bị dữ liệu đầu vào (X) và Nhãn mục tiêu (y)
X_train_full = df[['Car_Price', 'Age', 'Vehicle_Type', 'Level']].copy()
y_train_full = df['Label'].copy()

X_test_full = df_test_unseen[['Car_Price', 'Age', 'Vehicle_Type', 'Level']].copy()
y_test_full = df_test_unseen['Label'].copy()

# 3. QUY TRÌNH VÀNG: Gọi .fit() trên Pipeline
# Quy trình này thực hiện: fit_transform tiền xử lý trên tập Train -> Dùng kết quả đó huấn luyện Mô hình classifier
full_pipeline.fit(X_train_full, y_train_full)
print("-> Pipeline đã được Fit thành công trên dữ liệu huấn luyện!")

# 4. Dự đoán hoặc Đánh giá tập Test trực tiếp
# Pipeline tự động gọi .transform() dựa trên các thông số đã học từ Train, tuyệt đối không bị rò rỉ dữ liệu Test
predictions = full_pipeline.predict(X_test_full)

print("\nKết quả dự đoán nhãn cho tập Test thực tế:")
print(predictions)

=== BÀI 4: XÂY DỰNG PIPELINE TỰ ĐỘNG CHỐNG RÒ RỈ ===
-> Pipeline đã được Fit thành công trên dữ liệu huấn luyện!

Kết quả dự đoán nhãn cho tập Test thực tế:
['bird' 'dog']